### ISSUE TITLE
Unable to install on OpenWRT CC.

### ISSUE THREAD

**Issue by ObaidAshraf** [apollo-ng/luci-theme-darkmatter#15]
Hello,
I have a TPLink-WDR3500 router with OpenWRT CC in it. The firmware is the generic one from OpenWRT and i haven't modified (rebuilded) it.
I am trying to install this theme via command: opkg install /luci-theme-darkmatter_0.2-beta-2_all.ipk ... But, it is showing me this error:
 pkg_init_from_file: Malformed package file /luci-theme-darkmatter_0.2-beta-2_all.ipk.
Kindly let me know if i am making an error somewhere.
I am using OpenWRT CC (r46767)

**Comment by chron0** [comment]
Hmm, IIRC there was a change in the pkg structure between CC and the LEDE move. Since I was trying to get it committed upstream, I was forced to update it to adhere to what they wanted. Unfortunately someone got a bazoo stuck up his ganji so it never got accepted. If I find the time, I can try to set up an old CC build env and try to rebuild the ipk for CC. So I don't think you're doing something wrong there, it's just compatibility issues introduced be the turmoil in the LEDE/OpenWRT ecosphere. You can try to build your own FW with darkmatter as well, my experience showed that it's way better to bundle everything into the FW to begin with, instead of doing opkg installs afterwards.

**Comment by ObaidAshraf** [comment]
Is there any old version that worked with CC ?? So that i can use that .ipk and won't have to build it :) ..

**Comment by ObaidAshraf** [comment]
I compiled it with OpenWRT trunk and it worked fine .. 
Thankyou .. 
Closing the issue.

**Comment by chron0** [comment]
Awesome, thx for reporting back. Distributing ipks is tricky, that's why I released the sources.
